apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uzr47r5wu-java-springboot
  janus-idp.io/tekton: uzr47r5wu-java-springboot
  backstage.io/kubernetes-id: uzr47r5wu-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: uzr47r5wu-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
