apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uzr47r5wu-java-springboot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uzr47r5wu-java-springboot 
  name: uzr47r5wu-java-springboot
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uzr47r5wu-java-springboot 
